sudo: required
services:
    - docker
before_install:
    - docker build -t hussnainjav3d/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run hussnainjav3d/react-test npm test -- --coverage --watchAll=false
after_success:
    - docker build -t hussnainjav3d/multi-client ./client
    - docker build -t hussnainjav3d/multi-nginx ./nginx
    - docker build -t hussnainjav3d/multi-server ./server
    - docker build -t hussnainjav3d/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push hussnainjav3d/multi-client
    - docker push hussnainjav3d/multi-nginx 
    - docker push hussnainjav3d/multi-server
    - docker push hussnainjav3d/multi-worker